### ISSUE TITLE
decodeBC3 bug - artifacts on some DXT5 textures

### ISSUE THREAD

**Issue by Muxeu** [kchapelier/dxt#1]
Thanks for library. I just ported it to haxe and found one small bug:

utils.interpolateColorValues has next check:
```
if (isDxt1 && firstVal <= secondVal) {
...
} else if (firstVal > secondVal) {
...
}
```

When i decode some of DXT5 textures both of this check fails and function result array "colorValues" length is 0. As result, pixels colors become 'NaN' and result texture has artifacts.

Just changing code to:
```
if (isDxt1 || firstVal <= secondVal) {
...
} else if (firstVal > secondVal) {
...
}
```
fixed a bug.

**Comment by kchapelier** [comment]
Thanks for raising the issue and providing a fix.

I'm wondering if the fix shouldn't be the removal of the condition in the else instead (I haven't deal with DXT textures in a while...).

```js
if (isDxt1 && firstVal <= secondVal) {
 // ...
} else {
  // ...
}
```

I will look further into it.

**Comment by kchapelier** [comment]
Yes, the correct fix is to remove the conditions in the else (see the commit). Replacing the `&&` with `||` will break the DXT1 decoding.

@Muxeu Can you confirm this is working as expected in your port too ?

**Comment by Muxeu** [comment]
@kchapelier, yes, it does.  Thanks a lot.
